// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe1EKKulI4wCEeILdmCFqDwJ9LhPbRW3M',
    appId: '1:238985918902:web:6e2234391d1b8e5ecda917',
    messagingSenderId: '238985918902',
    projectId: 'yalasafari-84d14',
    authDomain: 'yalasafari-84d14.firebaseapp.com',
    storageBucket: 'yalasafari-84d14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpggPTmf3nkRu6JC9cBjbCG6KIVIu9FSc',
    appId: '1:452275219744:android:1e701ee3dfc720af13fb45',
    messagingSenderId: '452275219744',
    projectId: 'yala-driver-app1',
    storageBucket: 'yala-driver-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLIPZVJkQUhppGZAjc2PqOPvFlt5M30Y8',
    appId: '1:452275219744:ios:ee3ea81665d1830313fb45',
    messagingSenderId: '452275219744',
    projectId: 'yala-driver-app1',
    storageBucket: 'yala-driver-app1.firebasestorage.app',
    iosBundleId: 'com.example.yalaDriverApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA9pIpLYIAlGb4fThOYOmo6rnpBzTV6nw',
    appId: '1:238985918902:ios:f809020ba2700f05cda917',
    messagingSenderId: '238985918902',
    projectId: 'yalasafari-84d14',
    storageBucket: 'yalasafari-84d14.firebasestorage.app',
    iosBundleId: 'com.example.yalaDriverApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe1EKKulI4wCEeILdmCFqDwJ9LhPbRW3M',
    appId: '1:238985918902:web:b820a51a7ae1bbbecda917',
    messagingSenderId: '238985918902',
    projectId: 'yalasafari-84d14',
    authDomain: 'yalasafari-84d14.firebaseapp.com',
    storageBucket: 'yalasafari-84d14.firebasestorage.app',
  );

}